version: "3"
services:
  api:
    build: tools/devops/build/backend.Dockerfile
    image: mostafa8026/tribe-telegram-app-api
    container_name: tribe-telegram-app-api
    ports:
      - 3333:${PORT}
