version: "3"
services:
  api:
    build:
      context: ../../../
      dockerfile: tools/devops/build/backend.Dockerfile
    image: mostafa8026/tribe-telegram-app-api
    container_name: tribe-telegram-app-api
    restart: always
    environment:
      PORT: 3333
      TYPEORM_CONNECTION: mssql
      TYPEORM_HOST: db
      TYPEORM_PORT: 1433
      TYPEORM_USERNAME: sa
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_DATABASE: tribe
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_DRIVER_EXTRA: "{\"encrypt\": false}"
      # TOKEN
      GRAPHQL_URL: ${GRAPHQL_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SIGNING_SECRET: ${SIGNING_SECRET}
      NETWORK_ID: ${NETWORK_ID}
      MEMBER_ID: ${MEMBER_ID}

      # BOT
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
    ports:
      - 3333:3333
  db:
    build:
      context: ../../../
      dockerfile: tools/devops/build/mssql/mssql.Dockerfile
    image: mostafa8026/mssql-tribe
    container_name: db
    restart: always
    environment:
      SA_PASSWORD: ${TYPEORM_PASSWORD}
      ACCEPT_EULA: Y
    volumes:
      - mssql_vol:/var/opt/mssql
volumes:
  mssql_vol:
    name: mssql_vol

